name: "6. .NET Format Analysis"

on:
  push:
    branches: [ edson ]
  pull_request:
    branches: [ edson ]

jobs:
  format-check:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format
        
      - name: Check code formatting
        run: dotnet format --verify-no-changes --verbosity diagnostic