name: CodeQL Analysis

on:
  push:
    branches: [Derek]
  schedule:
    - cron: '0 0 * * 0' # cada domingo

jobs:
  analyze:
    name: CodeQL Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [csharp]

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Ejecutar análisis
        uses: github/codeql-action/analyze@v2
