name: "3. .NET Version Check"

on:
  push:
    branches: [ ANDERSON ]
  pull_request:
    branches: [ ANDERSON ]

jobs:
  dotnet-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Check .NET version
        run: dotnet --version
