name: "4. .NET Build"

on:
  push:
    branches: [ ANDERSON ]
  pull_request:
    branches: [ ANDERSON ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore dependencies
        run: |
          cd APILABORATORIO
          dotnet restore
          
      - name: Build project
        run: |
          cd APILABORATORIO
          dotnet build --no-restore --configuration Release
