name: "4. .NET Build"

on:
  push:
    branches: [ ANDERSON ]
  pull_request:
    branches: [ ANDERSON ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Find project file
        run: find . -name "*.csproj" -type f
        
      - name: Restore dependencies
        run: dotnet restore APILABORATORIO.csproj
        
      - name: Build project
        run: dotnet build APILABORATORIO.csproj --no-restore --configuration Release
