name: "7. CodeQL Security Analysis"

on:
  push:
    branches: [ edson ]
  pull_request:
    branches: [ edson ]
  schedule:
    - cron: '0 0 * * 0'  # Ejecutar semanalmente

jobs:
  analyze:
    name: Analyze C# Code
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        queries: security-and-quality

    - name: Autobuild C#
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{ matrix.language }}"