name: Analisis Estático y Seguridad

on:
  push:
    branches:
      - Derek

jobs:
  # 🔍 Roslyn Format Check (C#)
  roslyn-format:
    name: Verificar formato C#
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restaurar dependencias
        run: dotnet restore
        working-directory: ./APILABORATORIO

      - name: Verificar formato con Roslyn
        run: dotnet format --verify-no-changes
        working-directory: ./APILABORATORIO

  # 🛡️ CodeQL Security Scan (C#)
  codeql-analysis:
    name: Análisis de seguridad C#
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp

      - name: Ejecutar análisis
        uses: github/codeql-action/analyze@v2

  # 🧠 PHPStan (Laravel)
  phpstan:
    name: Análisis PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar PHP y Composer
        run: |
          sudo apt update
          sudo apt install php-cli unzip curl -y
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Instalar dependencias Laravel
        run: composer install
        working-directory: ./LaboratorioApp

      - name: Ejecutar PHPStan
        run: vendor/bin/phpstan analyse app/ --level=max
        working-directory: ./LaboratorioApp

  # 🎨 Laravel Pint
  pint-style:
    name: Validación de estilo Laravel
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar PHP y Composer
        run: |
          sudo apt update
          sudo apt install php-cli unzip curl -y
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Instalar dependencias Laravel
        run: composer install
        working-directory: ./LaboratorioApp

      - name: Ejecutar Laravel Pint
        run: ./vendor/bin/pint --test
        working-directory: ./LaboratorioApp
