name: "2. Multi OS Check"

on:
  push:
    branches: [ edson ]
  pull_request:
    branches: [ edson ]

jobs:
  check-os:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check OS info
        run: |
          echo "Sistema operativo: ${{ matrix.os }}"
          uname -a